module.exports.INVOICE_STATUS = {
    UNPAID: 'UNPAID'
}

module.exports.TRANSACTION_STATUS = {
    INITIATED: 'INITIATED'
}

module.exports.OFFICER_TYPE = {
    FIELD_OFFICER: 'FIELD_OFFICER',
    ADMINISTRATOR: 'ADMINISTRATOR'
}